-- TITAN v7: patch main_category + sub_category on existing releases
-- Safe to run multiple times on an existing database

ALTER TABLE releases ADD COLUMN IF NOT EXISTS main_category TEXT;
ALTER TABLE releases ADD COLUMN IF NOT EXISTS sub_category TEXT;

UPDATE releases SET main_category = 'schoenen', sub_category = 'limited-sneakers' WHERE slug = 'dunk-low-snkrs-nl-live';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'surging-sparks-bundle-soon';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'taylor-antwerp-presale';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'taylor-swift-london-jun-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'coldplay-paris-jul-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'drake-toronto-aug-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'travis-scott-houston-sep-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'beyonce-la-oct-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'bad-bunny-madrid-nov-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'billie-eilish-berlin-dec-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'ed-sheeran-manchester-jan-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'dua-lipa-amsterdam-feb-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'the-weeknd-brussels-mar-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'arctic-monkeys-dublin-apr-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'post-malone-vienna-may-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'sza-stockholm-jun-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'olivia-rodrigo-rome-jul-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'harry-styles-copenhagen-aug-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'metallica-munich-sep-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'adele-london-oct-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'kendrick-chicago-nov-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'rosalia-barcelona-dec-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'florence-lisbon-jan-2028';
UPDATE releases SET main_category = 'tickets', sub_category = 'american-sports' WHERE slug = 'super-bowl-lxi-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'football' WHERE slug = 'ucl-final-2026-munich';
UPDATE releases SET main_category = 'tickets', sub_category = 'football' WHERE slug = 'world-cup-final-2026-nyc';
UPDATE releases SET main_category = 'tickets', sub_category = 'football' WHERE slug = 'el-clasico-apr-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'pl-arsenal-liverpool-aug-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'american-sports' WHERE slug = 'nba-finals-game7-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'tennis-other' WHERE slug = 'f1-monaco-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'ufc-320-las-vegas-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'tennis-other' WHERE slug = 'wimbledon-final-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'festivals' WHERE slug = 'tomorrowland-2026-w1';
UPDATE releases SET main_category = 'tickets', sub_category = 'football' WHERE slug = 'six-nations-fr-ie-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'euroleague-final-four-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'tdf-champs-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'football' WHERE slug = 'jupiler-derby-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'tennis-other' WHERE slug = 'roland-garros-final-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'american-sports' WHERE slug = 'nhl-winter-classic-2027';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'indy-500-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'festivals' WHERE slug = 'glastonbury-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'copa-america-final-2026';
UPDATE releases SET main_category = 'tickets', sub_category = 'concerts' WHERE slug = 'olympics-opening-2028';
UPDATE releases SET main_category = 'schoenen', sub_category = 'collabs' WHERE slug = 'aj1-travis-medium-olive';
UPDATE releases SET main_category = 'schoenen', sub_category = 'limited-sneakers' WHERE slug = 'dunk-low-panda-restock';
UPDATE releases SET main_category = 'schoenen', sub_category = 'football-boots' WHERE slug = 'mercurial-superfly-elite';
UPDATE releases SET main_category = 'schoenen', sub_category = 'football-boots' WHERE slug = 'phantom-gx-elite';
UPDATE releases SET main_category = 'schoenen', sub_category = 'football-boots' WHERE slug = 'adidas-f50-elite';
UPDATE releases SET main_category = 'schoenen', sub_category = 'football-boots' WHERE slug = 'predator-elite-citrus';
UPDATE releases SET main_category = 'schoenen', sub_category = 'football-boots' WHERE slug = 'mercurial-vapor-16-se';
UPDATE releases SET main_category = 'overig', sub_category = 'fashion-drops' WHERE slug = 'nb550-ald';
UPDATE releases SET main_category = 'schoenen', sub_category = 'collabs' WHERE slug = 'air-max-1-og-red';
UPDATE releases SET main_category = 'schoenen', sub_category = 'limited-sneakers' WHERE slug = 'yeezy-slide-slate';
UPDATE releases SET main_category = 'schoenen', sub_category = 'limited-sneakers' WHERE slug = 'sb-dunk-jpack-chicago';
UPDATE releases SET main_category = 'schoenen', sub_category = 'running' WHERE slug = 'salomon-xt6-drop';
UPDATE releases SET main_category = 'schoenen', sub_category = 'running' WHERE slug = 'asics-kayano-14-silver';
UPDATE releases SET main_category = 'schoenen', sub_category = 'limited-sneakers' WHERE slug = 'af1-low-luxe';
UPDATE releases SET main_category = 'schoenen', sub_category = 'limited-sneakers' WHERE slug = 'jordan-4-military-blue';
UPDATE releases SET main_category = 'schoenen', sub_category = 'limited-sneakers' WHERE slug = 'samba-og-white';
UPDATE releases SET main_category = 'schoenen', sub_category = 'running' WHERE slug = 'vomero-5-photon';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'pokemon-charizard-collection';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'pokemon-151-upc';
UPDATE releases SET main_category = 'kaarten', sub_category = 'one-piece' WHERE slug = 'one-piece-op12-box';
UPDATE releases SET main_category = 'kaarten', sub_category = 'lorcana' WHERE slug = 'lorcana-ch8-collector';
UPDATE releases SET main_category = 'kaarten', sub_category = 'magic' WHERE slug = 'magic-secret-lair-doctor-who';
UPDATE releases SET main_category = 'kaarten', sub_category = 'yugioh' WHERE slug = 'yugioh-quarter-century';
UPDATE releases SET main_category = 'kaarten', sub_category = 'sports-cards' WHERE slug = 'topps-chrome-2026-hobby';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'pokemon-prismatic-etb';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'pokemon-paldean-fates-tin';
UPDATE releases SET main_category = 'kaarten', sub_category = 'one-piece' WHERE slug = 'one-piece-starter-ex';
UPDATE releases SET main_category = 'kaarten', sub_category = 'lorcana' WHERE slug = 'lorcana-illumineers-quest';
UPDATE releases SET main_category = 'kaarten', sub_category = 'magic' WHERE slug = 'magic-mh3-box';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'pokemon-crown-zenith-etb';
UPDATE releases SET main_category = 'kaarten', sub_category = 'yugioh' WHERE slug = 'yugioh-fire-kings-deck';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'pokemon-surging-sparks-bundle';
UPDATE releases SET main_category = 'kaarten', sub_category = 'pokemon' WHERE slug = 'pokemon-journey-together-etb';
UPDATE releases SET main_category = 'kaarten', sub_category = 'one-piece' WHERE slug = 'one-piece-op13-preorder';
UPDATE releases SET main_category = 'kaarten', sub_category = 'lorcana' WHERE slug = 'lorcana-ch9-starter';
UPDATE releases SET main_category = 'overig', sub_category = 'fashion-drops' WHERE slug = 'supreme-box-logo-fw26';
UPDATE releases SET main_category = 'overig', sub_category = 'fashion-drops' WHERE slug = 'palace-tri-ferg';
UPDATE releases SET main_category = 'overig', sub_category = 'gaming' WHERE slug = 'ps5-pro-bundle';
UPDATE releases SET main_category = 'overig', sub_category = 'gaming' WHERE slug = 'switch-2-launch';
UPDATE releases SET main_category = 'overig', sub_category = 'fashion-drops' WHERE slug = 'kith-bmw-collection';
UPDATE releases SET main_category = 'overig', sub_category = 'fashion-drops' WHERE slug = 'stussy-world-tour';
UPDATE releases SET main_category = 'schoenen', sub_category = 'collabs' WHERE slug = 'off-white-nike-terra';
UPDATE releases SET main_category = 'overig', sub_category = 'gaming' WHERE slug = 'xbox-series-x-elite';
UPDATE releases SET main_category = 'overig', sub_category = 'fashion-drops' WHERE slug = 'fog-essentials-drop';
UPDATE releases SET main_category = 'overig', sub_category = 'gaming' WHERE slug = 'steam-deck-oled-ltd';

-- Verify
SELECT main_category, sub_category, COUNT(*) FROM releases GROUP BY 1, 2 ORDER BY 1, 2;